### ISSUE TITLE
cheatcodes page part 1

### ISSUE THREAD

**Issue by flexbox** [realbenben/benoitpatou.fr#1]
## Layout

_Objective: Create a new page_

- [x] create a `cheatcode.html` page
- [x] Add the same layout as the others pages `index` and `switch`

## Conent

_Objective: Add content in json (because it's how computers api are talking together)_

- [x] create a `cheatcode.json` file with all the shortcuts like this

```json
export const allCheatcodes = [
  {
    "code": "..."
    "title": "...",
    "desctiption": "..."
  },
  {
    "code": "..."
    "title": "...",
    "desctiption": "..."
  },
]
```

## Add dynamic content to the page

_Objective: import data to a JavaScript file_

- [x] on `cheatcode.html` add a `div#js-cheatcode`
- [x] create a `cheatcode.js` file and import it on the page

```javascript
// cheatcode.js

import { allCheatcodes } from './cheatcode.json'
```

- [x] Add a `console.log(allCheatcodes)` to check if everything is connected

## Link this issue

_Objective: Do some magic_

- [x] Save and commit with this message "add cheatcode page closes #1" 🤯

**Comment by realbenben** [comment]
to boy je suis arrivée à la page .json je comprend pas ce que je dois mettre dans la section code 

  "code": "..."
    "title": "index.html",
    "desctiption": "main page"

**Comment by flexbox** [comment]
J'avoue c'est pas super explicite.

Là c'est meiux?

```json
export const allCheatcodes = [
  {
    "keyscode": "ctrl + shift + D"
    "desctiption": "sublime text dupliquer une ligne"
  },
  {
    "keyscode": "ctrl + D"
    "desctiption": "sublime text selectionner les memes caractères"
  },
  {
    "keyscode": "..."
    "desctiption": "..."
  },
]
```
