### ISSUE TITLE
cheatcode page part 2

### ISSUE THREAD

**Issue by flexbox** [realbenben/benoitpatou.fr#2]
## Create a JavaScript file

- [x] create a file `cheatcodes.js`
- [x] import with a script tag on the page `cheatcode.html`
- [x] put a `console.log('hello')` on your javascript file to check if everything is connected

## create an id 

- [x] `div#js-cheatcode` somewhere on the html page

## target the html element

_Objective: Where are we going to add our content_

- [x] target one HTML element with https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById
```javascript
const target = document.getElementById('js-cheatcode')
```

## Add some content

_Objective: write a dynamic loop to render all the elements_

```javascript
const allCheatcodesHTML = allCheatcodes.map((code) => {
    return `
      <p>
        <code>${code.code}</code>
        <strong>${code.title}</strong> : ${code.description}
      </p>
    `
  });
```

- [ ] Remplace the conent of our target with https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
```javascript
target.innerHTML = allCheatcodesHTML;
```

- [ ] commit and automatically close this issue

**Comment by flexbox** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/360936/90423164-4a1b5480-e0bc-11ea-8cb4-c9516dd7b930.png">
ça c'était correct

Il faut dans ta page `cheatcode.html`

```html
<div id="js-cheatcode"><div>
```

**Comment by realbenben** [comment]
Bizzarre je l'ai changer mais je l'ai remis comme tel avec le # . Je l'ai
bien comme ça dans mon code .
J'ai essayer de finir sans te solliciter mais galère galère... 😇

Le lun. 17 août 2020 à 19:04, David Leuliette <notifications@github.com> a
écrit :
